/*@ fixed */

#if defined(_MSC_VER)
  #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
  #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
  #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
  #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
  #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
  #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
  #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
  #pragma warning (disable:4307) // 'operator' : integral constant overflow
  #pragma warning (disable:4309) // 'conversion' : truncation of constant value
  #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
  #pragma warning (disable:4355) // 'this' : used in base member initializer list
  #pragma warning (disable:4506) // no definition for inline function 'function'
  #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
  #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
  #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessgae2.proto

#include "TestMessgae2.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace ProtobufBlueprintSp {
constexpr TestMessage2::TestMessage2(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : val_1_(0){}
struct TestMessage2DefaultTypeInternal {
  constexpr TestMessage2DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestMessage2DefaultTypeInternal() {}
  union {
    TestMessage2 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestMessage2DefaultTypeInternal _TestMessage2_default_instance_;
}  // namespace ProtobufBlueprintSp
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TestMessgae2_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TestMessgae2_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TestMessgae2_2eproto = nullptr;

const uint32_t TableStruct_TestMessgae2_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::TestMessage2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::TestMessage2, val_1_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ProtobufBlueprintSp::TestMessage2)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ProtobufBlueprintSp::_TestMessage2_default_instance_),
};

const char descriptor_table_protodef_TestMessgae2_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022TestMessgae2.proto\022\023ProtobufBlueprintS"
  "p\"\035\n\014TestMessage2\022\r\n\005val_1\030\001 \001(\005b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TestMessgae2_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMessgae2_2eproto = {
  false, false, 80, descriptor_table_protodef_TestMessgae2_2eproto, "TestMessgae2.proto", 
  &descriptor_table_TestMessgae2_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_TestMessgae2_2eproto::offsets,
  file_level_metadata_TestMessgae2_2eproto, file_level_enum_descriptors_TestMessgae2_2eproto, file_level_service_descriptors_TestMessgae2_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TestMessgae2_2eproto_getter() {
  return &descriptor_table_TestMessgae2_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TestMessgae2_2eproto(&descriptor_table_TestMessgae2_2eproto);
namespace ProtobufBlueprintSp {

// ===================================================================

class TestMessage2::_Internal {
 public:
};

TestMessage2::TestMessage2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:ProtobufBlueprintSp.TestMessage2)
}
TestMessage2::TestMessage2(const TestMessage2& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  val_1_ = from.val_1_;
  // @@protoc_insertion_point(copy_constructor:ProtobufBlueprintSp.TestMessage2)
}

inline void TestMessage2::SharedCtor() {
val_1_ = 0;
}

TestMessage2::~TestMessage2() {
  // @@protoc_insertion_point(destructor:ProtobufBlueprintSp.TestMessage2)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestMessage2::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TestMessage2::ArenaDtor(void* object) {
  TestMessage2* _this = reinterpret_cast< TestMessage2* >(object);
  (void)_this;
}
void TestMessage2::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestMessage2::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestMessage2::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtobufBlueprintSp.TestMessage2)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  val_1_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestMessage2::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 val_1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          val_1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestMessage2::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtobufBlueprintSp.TestMessage2)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 val_1 = 1;
  if (this->_internal_val_1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_val_1(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtobufBlueprintSp.TestMessage2)
  return target;
}

size_t TestMessage2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtobufBlueprintSp.TestMessage2)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 val_1 = 1;
  if (this->_internal_val_1() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_val_1());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestMessage2::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestMessage2::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestMessage2::GetClassData() const { return &_class_data_; }

void TestMessage2::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestMessage2 *>(to)->MergeFrom(
      static_cast<const TestMessage2 &>(from));
}


void TestMessage2::MergeFrom(const TestMessage2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtobufBlueprintSp.TestMessage2)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_val_1() != 0) {
    _internal_set_val_1(from._internal_val_1());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestMessage2::CopyFrom(const TestMessage2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtobufBlueprintSp.TestMessage2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessage2::IsInitialized() const {
  return true;
}

void TestMessage2::InternalSwap(TestMessage2* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(val_1_, other->val_1_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TestMessage2::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMessgae2_2eproto_getter, &descriptor_table_TestMessgae2_2eproto_once,
      file_level_metadata_TestMessgae2_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ProtobufBlueprintSp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ProtobufBlueprintSp::TestMessage2* Arena::CreateMaybeMessage< ::ProtobufBlueprintSp::TestMessage2 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProtobufBlueprintSp::TestMessage2 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
