/*@ fixed */

#if defined(_MSC_VER)
  #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
  #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
  #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
  #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
  #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
  #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
  #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
  #pragma warning (disable:4307) // 'operator' : integral constant overflow
  #pragma warning (disable:4309) // 'conversion' : truncation of constant value
  #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
  #pragma warning (disable:4355) // 'this' : used in base member initializer list
  #pragma warning (disable:4506) // no definition for inline function 'function'
  #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
  #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
  #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessage1.proto

#include "TestMessage1.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace ProtobufBlueprintSp {
constexpr TestMessage1::TestMessage1(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : val_1_(0)
  , val_2_(0){}
struct TestMessage1DefaultTypeInternal {
  constexpr TestMessage1DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestMessage1DefaultTypeInternal() {}
  union {
    TestMessage1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestMessage1DefaultTypeInternal _TestMessage1_default_instance_;
}  // namespace ProtobufBlueprintSp
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TestMessage1_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TestMessage1_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TestMessage1_2eproto = nullptr;

const uint32_t TableStruct_TestMessage1_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::TestMessage1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::TestMessage1, val_1_),
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::TestMessage1, val_2_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ProtobufBlueprintSp::TestMessage1)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ProtobufBlueprintSp::_TestMessage1_default_instance_),
};

const char descriptor_table_protodef_TestMessage1_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022TestMessage1.proto\022\023ProtobufBlueprintS"
  "p\",\n\014TestMessage1\022\r\n\005val_1\030\001 \001(\005\022\r\n\005val_"
  "2\030\002 \001(\005b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TestMessage1_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMessage1_2eproto = {
  false, false, 95, descriptor_table_protodef_TestMessage1_2eproto, "TestMessage1.proto", 
  &descriptor_table_TestMessage1_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_TestMessage1_2eproto::offsets,
  file_level_metadata_TestMessage1_2eproto, file_level_enum_descriptors_TestMessage1_2eproto, file_level_service_descriptors_TestMessage1_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TestMessage1_2eproto_getter() {
  return &descriptor_table_TestMessage1_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TestMessage1_2eproto(&descriptor_table_TestMessage1_2eproto);
namespace ProtobufBlueprintSp {

// ===================================================================

class TestMessage1::_Internal {
 public:
};

TestMessage1::TestMessage1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:ProtobufBlueprintSp.TestMessage1)
}
TestMessage1::TestMessage1(const TestMessage1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&val_1_, &from.val_1_,
    static_cast<size_t>(reinterpret_cast<char*>(&val_2_) -
    reinterpret_cast<char*>(&val_1_)) + sizeof(val_2_));
  // @@protoc_insertion_point(copy_constructor:ProtobufBlueprintSp.TestMessage1)
}

inline void TestMessage1::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&val_1_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&val_2_) -
    reinterpret_cast<char*>(&val_1_)) + sizeof(val_2_));
}

TestMessage1::~TestMessage1() {
  // @@protoc_insertion_point(destructor:ProtobufBlueprintSp.TestMessage1)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestMessage1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TestMessage1::ArenaDtor(void* object) {
  TestMessage1* _this = reinterpret_cast< TestMessage1* >(object);
  (void)_this;
}
void TestMessage1::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestMessage1::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestMessage1::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtobufBlueprintSp.TestMessage1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&val_1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&val_2_) -
      reinterpret_cast<char*>(&val_1_)) + sizeof(val_2_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestMessage1::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 val_1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          val_1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 val_2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          val_2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestMessage1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtobufBlueprintSp.TestMessage1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 val_1 = 1;
  if (this->_internal_val_1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_val_1(), target);
  }

  // int32 val_2 = 2;
  if (this->_internal_val_2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_val_2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtobufBlueprintSp.TestMessage1)
  return target;
}

size_t TestMessage1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtobufBlueprintSp.TestMessage1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 val_1 = 1;
  if (this->_internal_val_1() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_val_1());
  }

  // int32 val_2 = 2;
  if (this->_internal_val_2() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_val_2());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestMessage1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestMessage1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestMessage1::GetClassData() const { return &_class_data_; }

void TestMessage1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestMessage1 *>(to)->MergeFrom(
      static_cast<const TestMessage1 &>(from));
}


void TestMessage1::MergeFrom(const TestMessage1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtobufBlueprintSp.TestMessage1)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_val_1() != 0) {
    _internal_set_val_1(from._internal_val_1());
  }
  if (from._internal_val_2() != 0) {
    _internal_set_val_2(from._internal_val_2());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestMessage1::CopyFrom(const TestMessage1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtobufBlueprintSp.TestMessage1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessage1::IsInitialized() const {
  return true;
}

void TestMessage1::InternalSwap(TestMessage1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestMessage1, val_2_)
      + sizeof(TestMessage1::val_2_)
      - PROTOBUF_FIELD_OFFSET(TestMessage1, val_1_)>(
          reinterpret_cast<char*>(&val_1_),
          reinterpret_cast<char*>(&other->val_1_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TestMessage1::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMessage1_2eproto_getter, &descriptor_table_TestMessage1_2eproto_once,
      file_level_metadata_TestMessage1_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ProtobufBlueprintSp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ProtobufBlueprintSp::TestMessage1* Arena::CreateMaybeMessage< ::ProtobufBlueprintSp::TestMessage1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProtobufBlueprintSp::TestMessage1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
