/*@ fixed */

#if defined(_MSC_VER)
#pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
#pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
#pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
#pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
#pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
#pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
#pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
#pragma warning (disable:4307) // 'operator' : integral constant overflow
#pragma warning (disable:4309) // 'conversion' : truncation of constant value
#pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
#pragma warning (disable:4355) // 'this' : used in base member initializer list
#pragma warning (disable:4506) // no definition for inline function 'function'
#pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
#pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
#pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessage4.proto

#include "TestMessage4.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace protobuf {
constexpr TestSubMessage2::TestSubMessage2(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(0){}
struct TestSubMessage2DefaultTypeInternal {
  constexpr TestSubMessage2DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestSubMessage2DefaultTypeInternal() {}
  union {
    TestSubMessage2 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestSubMessage2DefaultTypeInternal _TestSubMessage2_default_instance_;
constexpr TestSubMessage1::TestSubMessage1(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sub_(nullptr)
  , id_(0){}
struct TestSubMessage1DefaultTypeInternal {
  constexpr TestSubMessage1DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestSubMessage1DefaultTypeInternal() {}
  union {
    TestSubMessage1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestSubMessage1DefaultTypeInternal _TestSubMessage1_default_instance_;
constexpr TestMessage4::TestMessage4(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sub_(nullptr)
  , id_(0){}
struct TestMessage4DefaultTypeInternal {
  constexpr TestMessage4DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestMessage4DefaultTypeInternal() {}
  union {
    TestMessage4 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestMessage4DefaultTypeInternal _TestMessage4_default_instance_;
}  // namespace protobuf
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TestMessage4_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TestMessage4_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TestMessage4_2eproto = nullptr;

const uint32_t TableStruct_TestMessage4_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestSubMessage2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestSubMessage2, id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestSubMessage1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestSubMessage1, id_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestSubMessage1, sub_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage4, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage4, id_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage4, sub_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protobuf::TestSubMessage2)},
  { 7, -1, -1, sizeof(::protobuf::TestSubMessage1)},
  { 15, -1, -1, sizeof(::protobuf::TestMessage4)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_TestSubMessage2_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_TestSubMessage1_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_TestMessage4_default_instance_),
};

const char descriptor_table_protodef_TestMessage4_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022TestMessage4.proto\022\010protobuf\"\035\n\017TestSu"
  "bMessage2\022\n\n\002id\030\001 \001(\005\"E\n\017TestSubMessage1"
  "\022\n\n\002id\030\001 \001(\005\022&\n\003sub\030\002 \001(\0132\031.protobuf.Tes"
  "tSubMessage2\"B\n\014TestMessage4\022\n\n\002id\030\001 \001(\005"
  "\022&\n\003sub\030\002 \001(\0132\031.protobuf.TestSubMessage1"
  "b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TestMessage4_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMessage4_2eproto = {
  false, false, 208, descriptor_table_protodef_TestMessage4_2eproto, "TestMessage4.proto", 
  &descriptor_table_TestMessage4_2eproto_once, nullptr, 0, 3,
  schemas, file_default_instances, TableStruct_TestMessage4_2eproto::offsets,
  file_level_metadata_TestMessage4_2eproto, file_level_enum_descriptors_TestMessage4_2eproto, file_level_service_descriptors_TestMessage4_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TestMessage4_2eproto_getter() {
  return &descriptor_table_TestMessage4_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TestMessage4_2eproto(&descriptor_table_TestMessage4_2eproto);
namespace protobuf {

// ===================================================================

class TestSubMessage2::_Internal {
 public:
};

TestSubMessage2::TestSubMessage2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:protobuf.TestSubMessage2)
}
TestSubMessage2::TestSubMessage2(const TestSubMessage2& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:protobuf.TestSubMessage2)
}

inline void TestSubMessage2::SharedCtor() {
id_ = 0;
}

TestSubMessage2::~TestSubMessage2() {
  // @@protoc_insertion_point(destructor:protobuf.TestSubMessage2)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestSubMessage2::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TestSubMessage2::ArenaDtor(void* object) {
  TestSubMessage2* _this = reinterpret_cast< TestSubMessage2* >(object);
  (void)_this;
}
void TestSubMessage2::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestSubMessage2::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestSubMessage2::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.TestSubMessage2)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestSubMessage2::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestSubMessage2::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.TestSubMessage2)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.TestSubMessage2)
  return target;
}

size_t TestSubMessage2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.TestSubMessage2)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestSubMessage2::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestSubMessage2::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestSubMessage2::GetClassData() const { return &_class_data_; }

void TestSubMessage2::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestSubMessage2 *>(to)->MergeFrom(
      static_cast<const TestSubMessage2 &>(from));
}


void TestSubMessage2::MergeFrom(const TestSubMessage2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.TestSubMessage2)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestSubMessage2::CopyFrom(const TestSubMessage2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.TestSubMessage2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestSubMessage2::IsInitialized() const {
  return true;
}

void TestSubMessage2::InternalSwap(TestSubMessage2* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(id_, other->id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TestSubMessage2::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMessage4_2eproto_getter, &descriptor_table_TestMessage4_2eproto_once,
      file_level_metadata_TestMessage4_2eproto[0]);
}

// ===================================================================

class TestSubMessage1::_Internal {
 public:
  static const ::protobuf::TestSubMessage2& sub(const TestSubMessage1* msg);
};

const ::protobuf::TestSubMessage2&
TestSubMessage1::_Internal::sub(const TestSubMessage1* msg) {
  return *msg->sub_;
}
TestSubMessage1::TestSubMessage1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:protobuf.TestSubMessage1)
}
TestSubMessage1::TestSubMessage1(const TestSubMessage1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_sub()) {
    sub_ = new ::protobuf::TestSubMessage2(*from.sub_);
  } else {
    sub_ = nullptr;
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:protobuf.TestSubMessage1)
}

inline void TestSubMessage1::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&sub_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&sub_)) + sizeof(id_));
}

TestSubMessage1::~TestSubMessage1() {
  // @@protoc_insertion_point(destructor:protobuf.TestSubMessage1)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestSubMessage1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete sub_;
}

void TestSubMessage1::ArenaDtor(void* object) {
  TestSubMessage1* _this = reinterpret_cast< TestSubMessage1* >(object);
  (void)_this;
}
void TestSubMessage1::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestSubMessage1::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestSubMessage1::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.TestSubMessage1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && sub_ != nullptr) {
    delete sub_;
  }
  sub_ = nullptr;
  id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestSubMessage1::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protobuf.TestSubMessage2 sub = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_sub(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestSubMessage1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.TestSubMessage1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // .protobuf.TestSubMessage2 sub = 2;
  if (this->_internal_has_sub()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::sub(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.TestSubMessage1)
  return target;
}

size_t TestSubMessage1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.TestSubMessage1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .protobuf.TestSubMessage2 sub = 2;
  if (this->_internal_has_sub()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *sub_);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestSubMessage1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestSubMessage1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestSubMessage1::GetClassData() const { return &_class_data_; }

void TestSubMessage1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestSubMessage1 *>(to)->MergeFrom(
      static_cast<const TestSubMessage1 &>(from));
}


void TestSubMessage1::MergeFrom(const TestSubMessage1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.TestSubMessage1)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_sub()) {
    _internal_mutable_sub()->::protobuf::TestSubMessage2::MergeFrom(from._internal_sub());
  }
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestSubMessage1::CopyFrom(const TestSubMessage1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.TestSubMessage1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestSubMessage1::IsInitialized() const {
  return true;
}

void TestSubMessage1::InternalSwap(TestSubMessage1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestSubMessage1, id_)
      + sizeof(TestSubMessage1::id_)
      - PROTOBUF_FIELD_OFFSET(TestSubMessage1, sub_)>(
          reinterpret_cast<char*>(&sub_),
          reinterpret_cast<char*>(&other->sub_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TestSubMessage1::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMessage4_2eproto_getter, &descriptor_table_TestMessage4_2eproto_once,
      file_level_metadata_TestMessage4_2eproto[1]);
}

// ===================================================================

class TestMessage4::_Internal {
 public:
  static const ::protobuf::TestSubMessage1& sub(const TestMessage4* msg);
};

const ::protobuf::TestSubMessage1&
TestMessage4::_Internal::sub(const TestMessage4* msg) {
  return *msg->sub_;
}
TestMessage4::TestMessage4(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:protobuf.TestMessage4)
}
TestMessage4::TestMessage4(const TestMessage4& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_sub()) {
    sub_ = new ::protobuf::TestSubMessage1(*from.sub_);
  } else {
    sub_ = nullptr;
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:protobuf.TestMessage4)
}

inline void TestMessage4::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&sub_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&sub_)) + sizeof(id_));
}

TestMessage4::~TestMessage4() {
  // @@protoc_insertion_point(destructor:protobuf.TestMessage4)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestMessage4::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete sub_;
}

void TestMessage4::ArenaDtor(void* object) {
  TestMessage4* _this = reinterpret_cast< TestMessage4* >(object);
  (void)_this;
}
void TestMessage4::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestMessage4::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestMessage4::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.TestMessage4)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && sub_ != nullptr) {
    delete sub_;
  }
  sub_ = nullptr;
  id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestMessage4::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protobuf.TestSubMessage1 sub = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_sub(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestMessage4::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.TestMessage4)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // .protobuf.TestSubMessage1 sub = 2;
  if (this->_internal_has_sub()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::sub(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.TestMessage4)
  return target;
}

size_t TestMessage4::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.TestMessage4)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .protobuf.TestSubMessage1 sub = 2;
  if (this->_internal_has_sub()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *sub_);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestMessage4::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestMessage4::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestMessage4::GetClassData() const { return &_class_data_; }

void TestMessage4::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestMessage4 *>(to)->MergeFrom(
      static_cast<const TestMessage4 &>(from));
}


void TestMessage4::MergeFrom(const TestMessage4& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.TestMessage4)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_sub()) {
    _internal_mutable_sub()->::protobuf::TestSubMessage1::MergeFrom(from._internal_sub());
  }
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestMessage4::CopyFrom(const TestMessage4& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.TestMessage4)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessage4::IsInitialized() const {
  return true;
}

void TestMessage4::InternalSwap(TestMessage4* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestMessage4, id_)
      + sizeof(TestMessage4::id_)
      - PROTOBUF_FIELD_OFFSET(TestMessage4, sub_)>(
          reinterpret_cast<char*>(&sub_),
          reinterpret_cast<char*>(&other->sub_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TestMessage4::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMessage4_2eproto_getter, &descriptor_table_TestMessage4_2eproto_once,
      file_level_metadata_TestMessage4_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::TestSubMessage2* Arena::CreateMaybeMessage< ::protobuf::TestSubMessage2 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::TestSubMessage2 >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::TestSubMessage1* Arena::CreateMaybeMessage< ::protobuf::TestSubMessage1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::TestSubMessage1 >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::TestMessage4* Arena::CreateMaybeMessage< ::protobuf::TestMessage4 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::TestMessage4 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
