/*@ fixed */

#if defined(_MSC_VER)
  #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
  #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
  #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
  #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
  #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
  #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
  #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
  #pragma warning (disable:4307) // 'operator' : integral constant overflow
  #pragma warning (disable:4309) // 'conversion' : truncation of constant value
  #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
  #pragma warning (disable:4355) // 'this' : used in base member initializer list
  #pragma warning (disable:4506) // no definition for inline function 'function'
  #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
  #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
  #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessage3.proto

#include "TestMessage3.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace protobuf {
constexpr TestMessage3::TestMessage3(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : val_string_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , val_bool_(false)
  , val_int32_(0)
  , val_int64_(int64_t{0})
  , val_uint32_(0u)
  , val_float_(0)
  , val_uint64_(uint64_t{0u})
  , val_double_(0)
  , val_enum_(0)
{}
struct TestMessage3DefaultTypeInternal {
  constexpr TestMessage3DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TestMessage3DefaultTypeInternal() {}
  union {
    TestMessage3 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TestMessage3DefaultTypeInternal _TestMessage3_default_instance_;
}  // namespace protobuf
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TestMessage3_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_TestMessage3_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TestMessage3_2eproto = nullptr;

const uint32_t TableStruct_TestMessage3_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_bool_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_int32_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_uint32_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_int64_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_uint64_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_float_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_double_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_string_),
  PROTOBUF_FIELD_OFFSET(::protobuf::TestMessage3, val_enum_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protobuf::TestMessage3)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_TestMessage3_default_instance_),
};

const char descriptor_table_protodef_TestMessage3_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022TestMessage3.proto\022\010protobuf\"\317\001\n\014TestM"
  "essage3\022\020\n\010val_bool\030\001 \001(\010\022\021\n\tval_int32\030\002"
  " \001(\005\022\022\n\nval_uint32\030\003 \001(\r\022\021\n\tval_int64\030\004 "
  "\001(\003\022\022\n\nval_uint64\030\005 \001(\004\022\021\n\tval_float\030\006 \001"
  "(\002\022\022\n\nval_double\030\007 \001(\001\022\022\n\nval_string\030\010 \001"
  "(\t\022$\n\010val_enum\030\t \001(\0162\022.protobuf.TestType"
  "*\037\n\010TestType\022\005\n\001A\020\000\022\005\n\001B\020\001\022\005\n\001C\020\002b\006proto"
  "3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TestMessage3_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMessage3_2eproto = {
  false, false, 281, descriptor_table_protodef_TestMessage3_2eproto, "TestMessage3.proto", 
  &descriptor_table_TestMessage3_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_TestMessage3_2eproto::offsets,
  file_level_metadata_TestMessage3_2eproto, file_level_enum_descriptors_TestMessage3_2eproto, file_level_service_descriptors_TestMessage3_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TestMessage3_2eproto_getter() {
  return &descriptor_table_TestMessage3_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TestMessage3_2eproto(&descriptor_table_TestMessage3_2eproto);
namespace protobuf {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TestType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_TestMessage3_2eproto);
  return file_level_enum_descriptors_TestMessage3_2eproto[0];
}
bool TestType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class TestMessage3::_Internal {
 public:
};

TestMessage3::TestMessage3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:protobuf.TestMessage3)
}
TestMessage3::TestMessage3(const TestMessage3& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  val_string_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    val_string_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_val_string().empty()) {
    val_string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_val_string(), 
      GetArenaForAllocation());
  }
  ::memcpy(&val_bool_, &from.val_bool_,
    static_cast<size_t>(reinterpret_cast<char*>(&val_enum_) -
    reinterpret_cast<char*>(&val_bool_)) + sizeof(val_enum_));
  // @@protoc_insertion_point(copy_constructor:protobuf.TestMessage3)
}

inline void TestMessage3::SharedCtor() {
val_string_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  val_string_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&val_bool_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&val_enum_) -
    reinterpret_cast<char*>(&val_bool_)) + sizeof(val_enum_));
}

TestMessage3::~TestMessage3() {
  // @@protoc_insertion_point(destructor:protobuf.TestMessage3)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TestMessage3::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  val_string_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TestMessage3::ArenaDtor(void* object) {
  TestMessage3* _this = reinterpret_cast< TestMessage3* >(object);
  (void)_this;
}
void TestMessage3::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestMessage3::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TestMessage3::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.TestMessage3)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  val_string_.ClearToEmpty();
  ::memset(&val_bool_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&val_enum_) -
      reinterpret_cast<char*>(&val_bool_)) + sizeof(val_enum_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestMessage3::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool val_bool = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          val_bool_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 val_int32 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          val_int32_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 val_uint32 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          val_uint32_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 val_int64 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          val_int64_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 val_uint64 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          val_uint64_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float val_float = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          val_float_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // double val_double = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          val_double_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // string val_string = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_val_string();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.TestMessage3.val_string"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protobuf.TestType val_enum = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_val_enum(static_cast<::protobuf::TestType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestMessage3::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.TestMessage3)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool val_bool = 1;
  if (this->_internal_val_bool() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_val_bool(), target);
  }

  // int32 val_int32 = 2;
  if (this->_internal_val_int32() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_val_int32(), target);
  }

  // uint32 val_uint32 = 3;
  if (this->_internal_val_uint32() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_val_uint32(), target);
  }

  // int64 val_int64 = 4;
  if (this->_internal_val_int64() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_val_int64(), target);
  }

  // uint64 val_uint64 = 5;
  if (this->_internal_val_uint64() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_val_uint64(), target);
  }

  // float val_float = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_val_float = this->_internal_val_float();
  uint32_t raw_val_float;
  memcpy(&raw_val_float, &tmp_val_float, sizeof(tmp_val_float));
  if (raw_val_float != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_val_float(), target);
  }

  // double val_double = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_val_double = this->_internal_val_double();
  uint64_t raw_val_double;
  memcpy(&raw_val_double, &tmp_val_double, sizeof(tmp_val_double));
  if (raw_val_double != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_val_double(), target);
  }

  // string val_string = 8;
  if (!this->_internal_val_string().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_val_string().data(), static_cast<int>(this->_internal_val_string().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.TestMessage3.val_string");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_val_string(), target);
  }

  // .protobuf.TestType val_enum = 9;
  if (this->_internal_val_enum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      9, this->_internal_val_enum(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.TestMessage3)
  return target;
}

size_t TestMessage3::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.TestMessage3)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string val_string = 8;
  if (!this->_internal_val_string().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_val_string());
  }

  // bool val_bool = 1;
  if (this->_internal_val_bool() != 0) {
    total_size += 1 + 1;
  }

  // int32 val_int32 = 2;
  if (this->_internal_val_int32() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_val_int32());
  }

  // int64 val_int64 = 4;
  if (this->_internal_val_int64() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_val_int64());
  }

  // uint32 val_uint32 = 3;
  if (this->_internal_val_uint32() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_val_uint32());
  }

  // float val_float = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_val_float = this->_internal_val_float();
  uint32_t raw_val_float;
  memcpy(&raw_val_float, &tmp_val_float, sizeof(tmp_val_float));
  if (raw_val_float != 0) {
    total_size += 1 + 4;
  }

  // uint64 val_uint64 = 5;
  if (this->_internal_val_uint64() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64SizePlusOne(this->_internal_val_uint64());
  }

  // double val_double = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_val_double = this->_internal_val_double();
  uint64_t raw_val_double;
  memcpy(&raw_val_double, &tmp_val_double, sizeof(tmp_val_double));
  if (raw_val_double != 0) {
    total_size += 1 + 8;
  }

  // .protobuf.TestType val_enum = 9;
  if (this->_internal_val_enum() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_val_enum());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestMessage3::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TestMessage3::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestMessage3::GetClassData() const { return &_class_data_; }

void TestMessage3::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TestMessage3 *>(to)->MergeFrom(
      static_cast<const TestMessage3 &>(from));
}


void TestMessage3::MergeFrom(const TestMessage3& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.TestMessage3)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_val_string().empty()) {
    _internal_set_val_string(from._internal_val_string());
  }
  if (from._internal_val_bool() != 0) {
    _internal_set_val_bool(from._internal_val_bool());
  }
  if (from._internal_val_int32() != 0) {
    _internal_set_val_int32(from._internal_val_int32());
  }
  if (from._internal_val_int64() != 0) {
    _internal_set_val_int64(from._internal_val_int64());
  }
  if (from._internal_val_uint32() != 0) {
    _internal_set_val_uint32(from._internal_val_uint32());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_val_float = from._internal_val_float();
  uint32_t raw_val_float;
  memcpy(&raw_val_float, &tmp_val_float, sizeof(tmp_val_float));
  if (raw_val_float != 0) {
    _internal_set_val_float(from._internal_val_float());
  }
  if (from._internal_val_uint64() != 0) {
    _internal_set_val_uint64(from._internal_val_uint64());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_val_double = from._internal_val_double();
  uint64_t raw_val_double;
  memcpy(&raw_val_double, &tmp_val_double, sizeof(tmp_val_double));
  if (raw_val_double != 0) {
    _internal_set_val_double(from._internal_val_double());
  }
  if (from._internal_val_enum() != 0) {
    _internal_set_val_enum(from._internal_val_enum());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestMessage3::CopyFrom(const TestMessage3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.TestMessage3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessage3::IsInitialized() const {
  return true;
}

void TestMessage3::InternalSwap(TestMessage3* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &val_string_, lhs_arena,
      &other->val_string_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestMessage3, val_enum_)
      + sizeof(TestMessage3::val_enum_)
      - PROTOBUF_FIELD_OFFSET(TestMessage3, val_bool_)>(
          reinterpret_cast<char*>(&val_bool_),
          reinterpret_cast<char*>(&other->val_bool_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TestMessage3::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TestMessage3_2eproto_getter, &descriptor_table_TestMessage3_2eproto_once,
      file_level_metadata_TestMessage3_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::TestMessage3* Arena::CreateMaybeMessage< ::protobuf::TestMessage3 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::TestMessage3 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
