/*@ fixed */

#if defined(_MSC_VER)
#pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessage4.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TestMessage4_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TestMessage4_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TestMessage4_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TestMessage4_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TestMessage4_2eproto;
namespace protobuf {
class TestMessage4;
struct TestMessage4DefaultTypeInternal;
extern TestMessage4DefaultTypeInternal _TestMessage4_default_instance_;
class TestSubMessage1;
struct TestSubMessage1DefaultTypeInternal;
extern TestSubMessage1DefaultTypeInternal _TestSubMessage1_default_instance_;
class TestSubMessage2;
struct TestSubMessage2DefaultTypeInternal;
extern TestSubMessage2DefaultTypeInternal _TestSubMessage2_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::TestMessage4* Arena::CreateMaybeMessage<::protobuf::TestMessage4>(Arena*);
template<> ::protobuf::TestSubMessage1* Arena::CreateMaybeMessage<::protobuf::TestSubMessage1>(Arena*);
template<> ::protobuf::TestSubMessage2* Arena::CreateMaybeMessage<::protobuf::TestSubMessage2>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class TestSubMessage2 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.TestSubMessage2) */ {
 public:
  inline TestSubMessage2() : TestSubMessage2(nullptr) {}
  ~TestSubMessage2() override;
  explicit constexpr TestSubMessage2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestSubMessage2(const TestSubMessage2& from);
  TestSubMessage2(TestSubMessage2&& from) noexcept
    : TestSubMessage2() {
    *this = ::std::move(from);
  }

  inline TestSubMessage2& operator=(const TestSubMessage2& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestSubMessage2& operator=(TestSubMessage2&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestSubMessage2& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestSubMessage2* internal_default_instance() {
    return reinterpret_cast<const TestSubMessage2*>(
               &_TestSubMessage2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TestSubMessage2& a, TestSubMessage2& b) {
    a.Swap(&b);
  }
  inline void Swap(TestSubMessage2* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestSubMessage2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestSubMessage2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestSubMessage2>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestSubMessage2& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TestSubMessage2& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestSubMessage2* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.TestSubMessage2";
  }
  protected:
  explicit TestSubMessage2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.TestSubMessage2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TestMessage4_2eproto;
};
// -------------------------------------------------------------------

class TestSubMessage1 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.TestSubMessage1) */ {
 public:
  inline TestSubMessage1() : TestSubMessage1(nullptr) {}
  ~TestSubMessage1() override;
  explicit constexpr TestSubMessage1(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestSubMessage1(const TestSubMessage1& from);
  TestSubMessage1(TestSubMessage1&& from) noexcept
    : TestSubMessage1() {
    *this = ::std::move(from);
  }

  inline TestSubMessage1& operator=(const TestSubMessage1& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestSubMessage1& operator=(TestSubMessage1&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestSubMessage1& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestSubMessage1* internal_default_instance() {
    return reinterpret_cast<const TestSubMessage1*>(
               &_TestSubMessage1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TestSubMessage1& a, TestSubMessage1& b) {
    a.Swap(&b);
  }
  inline void Swap(TestSubMessage1* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestSubMessage1* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestSubMessage1* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestSubMessage1>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestSubMessage1& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TestSubMessage1& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestSubMessage1* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.TestSubMessage1";
  }
  protected:
  explicit TestSubMessage1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // .protobuf.TestSubMessage2 sub = 2;
  bool has_sub() const;
  private:
  bool _internal_has_sub() const;
  public:
  void clear_sub();
  const ::protobuf::TestSubMessage2& sub() const;
  PROTOBUF_NODISCARD ::protobuf::TestSubMessage2* release_sub();
  ::protobuf::TestSubMessage2* mutable_sub();
  void set_allocated_sub(::protobuf::TestSubMessage2* sub);
  private:
  const ::protobuf::TestSubMessage2& _internal_sub() const;
  ::protobuf::TestSubMessage2* _internal_mutable_sub();
  public:
  void unsafe_arena_set_allocated_sub(
      ::protobuf::TestSubMessage2* sub);
  ::protobuf::TestSubMessage2* unsafe_arena_release_sub();

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.TestSubMessage1)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::protobuf::TestSubMessage2* sub_;
  int32_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TestMessage4_2eproto;
};
// -------------------------------------------------------------------

class TestMessage4 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.TestMessage4) */ {
 public:
  inline TestMessage4() : TestMessage4(nullptr) {}
  ~TestMessage4() override;
  explicit constexpr TestMessage4(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestMessage4(const TestMessage4& from);
  TestMessage4(TestMessage4&& from) noexcept
    : TestMessage4() {
    *this = ::std::move(from);
  }

  inline TestMessage4& operator=(const TestMessage4& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMessage4& operator=(TestMessage4&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestMessage4& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestMessage4* internal_default_instance() {
    return reinterpret_cast<const TestMessage4*>(
               &_TestMessage4_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TestMessage4& a, TestMessage4& b) {
    a.Swap(&b);
  }
  inline void Swap(TestMessage4* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMessage4* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestMessage4* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestMessage4>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestMessage4& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TestMessage4& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestMessage4* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.TestMessage4";
  }
  protected:
  explicit TestMessage4(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // .protobuf.TestSubMessage1 sub = 2;
  bool has_sub() const;
  private:
  bool _internal_has_sub() const;
  public:
  void clear_sub();
  const ::protobuf::TestSubMessage1& sub() const;
  PROTOBUF_NODISCARD ::protobuf::TestSubMessage1* release_sub();
  ::protobuf::TestSubMessage1* mutable_sub();
  void set_allocated_sub(::protobuf::TestSubMessage1* sub);
  private:
  const ::protobuf::TestSubMessage1& _internal_sub() const;
  ::protobuf::TestSubMessage1* _internal_mutable_sub();
  public:
  void unsafe_arena_set_allocated_sub(
      ::protobuf::TestSubMessage1* sub);
  ::protobuf::TestSubMessage1* unsafe_arena_release_sub();

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.TestMessage4)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::protobuf::TestSubMessage1* sub_;
  int32_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TestMessage4_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestSubMessage2

// int32 id = 1;
inline void TestSubMessage2::clear_id() {
  id_ = 0;
}
inline int32_t TestSubMessage2::_internal_id() const {
  return id_;
}
inline int32_t TestSubMessage2::id() const {
  // @@protoc_insertion_point(field_get:protobuf.TestSubMessage2.id)
  return _internal_id();
}
inline void TestSubMessage2::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void TestSubMessage2::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:protobuf.TestSubMessage2.id)
}

// -------------------------------------------------------------------

// TestSubMessage1

// int32 id = 1;
inline void TestSubMessage1::clear_id() {
  id_ = 0;
}
inline int32_t TestSubMessage1::_internal_id() const {
  return id_;
}
inline int32_t TestSubMessage1::id() const {
  // @@protoc_insertion_point(field_get:protobuf.TestSubMessage1.id)
  return _internal_id();
}
inline void TestSubMessage1::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void TestSubMessage1::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:protobuf.TestSubMessage1.id)
}

// .protobuf.TestSubMessage2 sub = 2;
inline bool TestSubMessage1::_internal_has_sub() const {
  return this != internal_default_instance() && sub_ != nullptr;
}
inline bool TestSubMessage1::has_sub() const {
  return _internal_has_sub();
}
inline void TestSubMessage1::clear_sub() {
  if (GetArenaForAllocation() == nullptr && sub_ != nullptr) {
    delete sub_;
  }
  sub_ = nullptr;
}
inline const ::protobuf::TestSubMessage2& TestSubMessage1::_internal_sub() const {
  const ::protobuf::TestSubMessage2* p = sub_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::TestSubMessage2&>(
      ::protobuf::_TestSubMessage2_default_instance_);
}
inline const ::protobuf::TestSubMessage2& TestSubMessage1::sub() const {
  // @@protoc_insertion_point(field_get:protobuf.TestSubMessage1.sub)
  return _internal_sub();
}
inline void TestSubMessage1::unsafe_arena_set_allocated_sub(
    ::protobuf::TestSubMessage2* sub) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sub_);
  }
  sub_ = sub;
  if (sub) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.TestSubMessage1.sub)
}
inline ::protobuf::TestSubMessage2* TestSubMessage1::release_sub() {
  
  ::protobuf::TestSubMessage2* temp = sub_;
  sub_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::protobuf::TestSubMessage2* TestSubMessage1::unsafe_arena_release_sub() {
  // @@protoc_insertion_point(field_release:protobuf.TestSubMessage1.sub)
  
  ::protobuf::TestSubMessage2* temp = sub_;
  sub_ = nullptr;
  return temp;
}
inline ::protobuf::TestSubMessage2* TestSubMessage1::_internal_mutable_sub() {
  
  if (sub_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::TestSubMessage2>(GetArenaForAllocation());
    sub_ = p;
  }
  return sub_;
}
inline ::protobuf::TestSubMessage2* TestSubMessage1::mutable_sub() {
  ::protobuf::TestSubMessage2* _msg = _internal_mutable_sub();
  // @@protoc_insertion_point(field_mutable:protobuf.TestSubMessage1.sub)
  return _msg;
}
inline void TestSubMessage1::set_allocated_sub(::protobuf::TestSubMessage2* sub) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete sub_;
  }
  if (sub) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::protobuf::TestSubMessage2>::GetOwningArena(sub);
    if (message_arena != submessage_arena) {
      sub = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sub, submessage_arena);
    }
    
  } else {
    
  }
  sub_ = sub;
  // @@protoc_insertion_point(field_set_allocated:protobuf.TestSubMessage1.sub)
}

// -------------------------------------------------------------------

// TestMessage4

// int32 id = 1;
inline void TestMessage4::clear_id() {
  id_ = 0;
}
inline int32_t TestMessage4::_internal_id() const {
  return id_;
}
inline int32_t TestMessage4::id() const {
  // @@protoc_insertion_point(field_get:protobuf.TestMessage4.id)
  return _internal_id();
}
inline void TestMessage4::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void TestMessage4::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:protobuf.TestMessage4.id)
}

// .protobuf.TestSubMessage1 sub = 2;
inline bool TestMessage4::_internal_has_sub() const {
  return this != internal_default_instance() && sub_ != nullptr;
}
inline bool TestMessage4::has_sub() const {
  return _internal_has_sub();
}
inline void TestMessage4::clear_sub() {
  if (GetArenaForAllocation() == nullptr && sub_ != nullptr) {
    delete sub_;
  }
  sub_ = nullptr;
}
inline const ::protobuf::TestSubMessage1& TestMessage4::_internal_sub() const {
  const ::protobuf::TestSubMessage1* p = sub_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::TestSubMessage1&>(
      ::protobuf::_TestSubMessage1_default_instance_);
}
inline const ::protobuf::TestSubMessage1& TestMessage4::sub() const {
  // @@protoc_insertion_point(field_get:protobuf.TestMessage4.sub)
  return _internal_sub();
}
inline void TestMessage4::unsafe_arena_set_allocated_sub(
    ::protobuf::TestSubMessage1* sub) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sub_);
  }
  sub_ = sub;
  if (sub) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.TestMessage4.sub)
}
inline ::protobuf::TestSubMessage1* TestMessage4::release_sub() {
  
  ::protobuf::TestSubMessage1* temp = sub_;
  sub_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::protobuf::TestSubMessage1* TestMessage4::unsafe_arena_release_sub() {
  // @@protoc_insertion_point(field_release:protobuf.TestMessage4.sub)
  
  ::protobuf::TestSubMessage1* temp = sub_;
  sub_ = nullptr;
  return temp;
}
inline ::protobuf::TestSubMessage1* TestMessage4::_internal_mutable_sub() {
  
  if (sub_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::TestSubMessage1>(GetArenaForAllocation());
    sub_ = p;
  }
  return sub_;
}
inline ::protobuf::TestSubMessage1* TestMessage4::mutable_sub() {
  ::protobuf::TestSubMessage1* _msg = _internal_mutable_sub();
  // @@protoc_insertion_point(field_mutable:protobuf.TestMessage4.sub)
  return _msg;
}
inline void TestMessage4::set_allocated_sub(::protobuf::TestSubMessage1* sub) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete sub_;
  }
  if (sub) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::protobuf::TestSubMessage1>::GetOwningArena(sub);
    if (message_arena != submessage_arena) {
      sub = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sub, submessage_arena);
    }
    
  } else {
    
  }
  sub_ = sub;
  // @@protoc_insertion_point(field_set_allocated:protobuf.TestMessage4.sub)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TestMessage4_2eproto
